// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void slidein_Animation(lv_obj_t * TargetObject, int delay);
void Opacity_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_standbyscreen
void ui_standbyscreen_screen_init(void);
void ui_event_standbyscreen(lv_event_t * e);
extern lv_obj_t * ui_standbyscreen;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_lblDate;
extern lv_obj_t * ui_Label_Status;
extern lv_obj_t * ui_HomeScreen;
// CUSTOM VARIABLES

// SCREEN: ui_checkIDadMin
void ui_checkIDadMin_screen_init(void);
extern lv_obj_t * ui_checkIDadMin;
extern lv_obj_t * ui_imgwifistatus;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_kbLogin;
void ui_event_txtinput(lv_event_t * e);
extern lv_obj_t * ui_txtinput;
void ui_event_txtPassword(lv_event_t * e);
extern lv_obj_t * ui_txtPassword;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_114028185);    // assets/hinh-nen-desktop-58-ezgif.com-jpg-to-png-converter.png
LV_IMG_DECLARE(ui_img_493812277);    // assets/wifi-svgrepo-com-ezgif.com-resize.png
LV_IMG_DECLARE(ui_img_1308773787);    // assets/wifi-slash-svgrepo-com-ezgif.com-resize.png
LV_IMG_DECLARE(ui_img_1614011454);    // assets/power-ezgif.com-resize.png
LV_IMG_DECLARE(ui_img_159797012);    // assets/signal-alt-2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
