// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "lvgl.h"

void ui_checkIDadMin_screen_init(void)
{
    ui_checkIDadMin = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_checkIDadMin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_checkIDadMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_checkIDadMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_checkIDadMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_checkIDadMin, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgwifistatus = lv_img_create(ui_checkIDadMin);
    lv_img_set_src(ui_imgwifistatus, &ui_img_493812277);
    lv_obj_set_width(ui_imgwifistatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgwifistatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgwifistatus, 142);
    lv_obj_set_y(ui_imgwifistatus, -102);
    lv_obj_set_align(ui_imgwifistatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgwifistatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgwifistatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_checkIDadMin);
    lv_img_set_src(ui_Image3, &ui_img_1308773787);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 142);
    lv_obj_set_y(ui_Image3, -102);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kbLogin = lv_keyboard_create(ui_checkIDadMin);
    lv_obj_set_width(ui_kbLogin, 315);
    lv_obj_set_height(ui_kbLogin, 120);
    lv_obj_set_x(ui_kbLogin, -1);
    lv_obj_set_y(ui_kbLogin, 58);
    lv_obj_set_align(ui_kbLogin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_kbLogin, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_scroll_dir(ui_kbLogin, LV_DIR_TOP);

    ui_txtinput = lv_textarea_create(ui_checkIDadMin);
    lv_obj_set_width(ui_txtinput, 320);
    lv_obj_set_height(ui_txtinput, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_txtinput, 0);
    lv_obj_set_y(ui_txtinput, -59);
    lv_obj_set_align(ui_txtinput, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtinput, "Ten dang nhap");
    lv_textarea_set_one_line(ui_txtinput, true);



    ui_txtPassword = lv_textarea_create(ui_checkIDadMin);
    lv_obj_set_width(ui_txtPassword, 320);
    lv_obj_set_height(ui_txtPassword, 30);
    lv_obj_set_x(ui_txtPassword, 0);
    lv_obj_set_y(ui_txtPassword, -22);
    lv_obj_set_align(ui_txtPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtPassword, "Mat khau");
    lv_textarea_set_one_line(ui_txtPassword, true);
    lv_textarea_set_password_mode(ui_txtPassword, true);

    lv_obj_t * eye_btn = lv_btn_create(ui_checkIDadMin);
    lv_obj_set_width(eye_btn, 40);
    lv_obj_set_height(eye_btn, 30);
    lv_obj_align_to(eye_btn, ui_txtPassword, LV_ALIGN_OUT_RIGHT_MID, 10, 0);
    lv_obj_add_event_cb(eye_btn, toggle_password_visibility, LV_EVENT_CLICKED, NULL);
    lv_label_set_text(lv_label_create(eye_btn), LV_SYMBOL_EYE);

    lv_obj_t * eye_btn = lv_btn_create(ui_checkIDadMin);
    lv_obj_set_size(eye_btn, 40, 30);
    lv_obj_align_to(eye_btn, ui_txtPassword, LV_ALIGN_OUT_RIGHT_MID, 10, 0);
    lv_obj_add_event_cb(eye_btn, toggle_password_visibility, LV_EVENT_CLICKED, NULL);
    lv_label_set_text(lv_label_create(eye_btn), LV_SYMBOL_EYE);



    ui_Button1 = lv_btn_create(ui_checkIDadMin);
    lv_obj_set_width(ui_Button1, 40);
    lv_obj_set_height(ui_Button1, 36);
    lv_obj_set_x(ui_Button1, -137);
    lv_obj_set_y(ui_Button1, -100);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0x00F9DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_1614011454, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_txtinput, ui_event_txtinput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtPassword, ui_event_txtPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
void update_wifi_status(bool connected) {
    if (connected) {
        lv_obj_clear_flag(ui_imgwifistatus, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_imgwifistatus, LV_OBJ_FLAG_HIDDEN);
    }
}

